driver:
  name: docker
  privileged: true
  use_sudo: false

# avoids to intermittent "Class: Kitchen::ActionFailed SCP upload failed (open failed (1))" errors
# https://github.com/test-kitchen/test-kitchen/issues/1035
transport:
  max_ssh_sessions: 6

platforms:
  - name: ubuntu-16.04

provisioner:
  name: ansible_playbook
  hosts: testing
  playbook: testing.yml
  ansible_verbose: true
#  ansible_version: latest
  require_ansible_repo: true        #required
  require_ansible_omnibus: false
  require_chef_for_busser: false
  additional_copy_path:
    - 'roles'

verifier:
  name: inspec
  format: documentation

suites:
  - name: default
    verifier:
      inspec_tests:
        - path: test/inspec
