language: ruby
sudo: required
services: docker
before_install:
- gem install bundler -v 1.10.6

install:
- bundle install --jobs=1

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER
script:

# integration tests
- bundle exec kitchen converge default-ubuntu-1604
- bundle exec kitchen verify default-ubuntu-1604
